package utn.TpFinal.AppUnTN.model;

public enum Subject {
    PROGRAMACION_I,
    ARQUITECTURA_Y_SISTEMAS_OPERATIVOS,
    MATEMATICA,
    ORGANIZACION_EMPRESARIAL,
    PROGRAMACION_II,
    PROBABILIDAD_Y_ESTADISTICA,
    BASE_DE_DATOS_II,
    INGLES_I,
    PROGRAMACION_III,
    BASE_DE_DATOS_I,
    METODOLOGIA_DE_SISTEMAS_I,
    INGLES_II,
    PROGRAMACION_IV,
    METODOLOGIA_DE_SISTEMAS_II,
    INTRODUCCION_AL_ANALISIS_DE_DATOS,
    LEGISLACION,
    GESTION_DE_DESARROLLO_DE_SOFTWARE,
}
