spring.application.name=AppUnTN
spring.datasource.url=jdbc:mysql://localhost:3306/appuntn
spring.datasource.username=root
spring.datasource.password=11Deenero.






spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

