spring.application.name=AppUnTN
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/appuntn}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:lautaro}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Tama�o m�ximo por archivo (ejemplo: 50MB)
spring.servlet.multipart.max-file-size=100MB

# Tama�o m�ximo de la solicitud completa
spring.servlet.multipart.max-request-size=100MB


